user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
